### PR TITLE
Add cropping to train and validation

### PR DESCRIPTION
**Pull request by hma02**
Add cropping to train and validation when para_load = False, and remove flag_datalayer=True condition, since flag_datalayer is actually not needed.

### CODE REVIEW

**Comment by gwding** [comment]
@hma02 you don't have to close the previous one and create a new one :)
simply push your changes to the same branch and the pull request will be updated

but we'll just work on this one.

Have you run a one / two day test on this to see if it works correctly?
if the curves looks right, we can merge it

**Comment by gwding** [comment]
seems this implementation is correct and give same results.
Let's merge it after all the comments like 

```
###BUG 1 FIXED#####
```

are removed

@hma02 just make changes in your branch and push it, the pull request will be updated

**Comment by hma02** [comment]
Sounds good. By the way I fixed another bug which I noticed before, that is in train.py but not in train_2gpu.py, the drv.init() should be called no matter it is para_load or not, otherwise it will give error when para_load= False

**Comment by gwding** [comment]
@hma02 nice extra fix!
regarding flag_batch, it seems that it should be there anymore? 
because we don't really need the flag_batch = True? because we always want to randomly crop and flip on a per image base?

**Comment by hma02** [comment]
Now the flag_batch = True is only used in validation, cropping the center of the image as input batch and giving a deterministic error evaluation, if this is what we are supposed to do. Also I think keeping it is still useful for deterministic debugging and checking correctness. It might be interesting to add another feature during validation, that is cropping on different part of the same photo to improve validation accuracy.

**Comment by gwding** [comment]
@hma02 good point, merged

**Pull request merged**
